### YamlMime:FAQ
metadata:
  title: Résoudre les problèmes de rôles Azure AD attribués aux groupes – Azure Active Directory
  description: Découvrez quelques questions courantes et des conseils de dépannage pour l’attribution de rôles à des groupes dans Azure Active Directory.
  services: active-directory
  author: rolyon
  manager: daveba
  ms.service: active-directory
  ms.workload: identity
  ms.subservice: roles
  ms.topic: article
  ms.date: 11/05/2020
  ms.author: rolyon
  ms.reviewer: vincesm
  ms.custom: it-pro
  ms.collection: M365-identity-device-management
  ms.openlocfilehash: c09bcdde3713f3ab93814cc67b23ded5cc49c17d
  ms.sourcegitcommit: 106f5c9fa5c6d3498dd1cfe63181a7ed4125ae6d
  ms.translationtype: HT
  ms.contentlocale: fr-FR
  ms.lasthandoff: 11/02/2021
  ms.locfileid: "131057131"
title: Résoudre les problèmes de rôles Azure AD attribués aux groupes
summary: Voici quelques questions courantes et des conseils de résolution des problèmes pour l’attribution de rôles Azure Active Directory (Azure AD) à des groupes Azure AD.
sections:
- name: Ignoré
  questions:
  - question: >
      Je suis administrateur de groupes, mais je ne vois pas le commutateur « Des rôles Azure AD peuvent être attribués au groupe ».
    answer: >
      Seuls les administrateurs de rôle privilégié ou les administrateurs généraux peuvent créer un groupe admissible à l’attribution de rôle. Seuls les utilisateurs de ces rôles voient ce contrôle.
  - question: >
      Qui peut modifier l’appartenance des groupes qui sont affectés à des rôles Azure AD ?
    answer: >
      Par défaut, seul l’Administrateur de rôle privilégié ou l’Administrateur général peut gérer l’appartenance à un groupe assignable à un rôle, mais vous pouvez déléguer la gestion des groupes assignables à un rôle en leur ajoutant des propriétaires de groupe.
  - question: >
      Je suis Administrateur du support technique dans mon organisation, mais je ne peux pas mettre à jour le mot de passe d’un utilisateur ayant le rôle Lecteurs de répertoire. Pourquoi cela se produit-il ?
    answer: >
      L’utilisateur a peut-être obtenu le rôle Lecteurs de répertoire par le biais d’un groupe assignable à un rôle. Tous les membres et propriétaires d’un groupe assignable à un rôle sont protégés. Seuls les utilisateurs ayant les rôles Administrateur d’authentification privilégiée ou Administrateur général peuvent réinitialiser les informations d’identification d’un utilisateur protégé.
  - question: >
      Je ne parviens pas à mettre à jour le mot de passe d’un utilisateur. Aucun rôle privilégié plus élevé ne lui est attribué. Pourquoi cela se passe-t-il ?
    answer: "L’utilisateur peut être propriétaire d’un groupe assignable à un rôle. Nous protégeons les propriétaires de ces groupes afin d’empêcher une élévation de privilèges. Prenons l'exemple du groupe Contoso_Security_Admins, qui dispose du rôle Administrateur de la sécurité, et où Bob est le propriétaire du groupe tandis qu'Alice est Administrateur de mot de passe au sein de l'organisation. Si cette protection n’était pas présente, Alice pourrait réinitialiser les informations d’identification de Bob et prendre le contrôle de son identité. Ensuite, Alice pourrait s'ajouter elle-même ou ajouter toute autre personne au groupe Contoso_Security_Admins pour devenir Administrateur de la sécurité au sein de l'organisation. Pour déterminer si un utilisateur est propriétaire d’un groupe, obtenez la liste des objets détenus de cet utilisateur et vérifiez si isAssignableToRole a la valeur true pour l’un des groupes. Si c’est le cas, cet utilisateur est protégé et le comportement est normal. Reportez-vous à ces documents pour obtenir les objets détenus :\n\n- [Get-AzureADUserOwnedObject](/powershell/module/azuread/get-azureaduserownedobject)  \n- [List ownedObjects](/graph/api/user-list-ownedobjects?tabs=http)\n"
  - question: "Puis-je créer une révision d’accès sur des groupes qui peuvent être affectés à des rôles Azure AD (plus précisément, les groupes dont la propriété isAssignableToRole est définie sur true) ?  \n"
    answer: >
      Oui, vous pouvez. Les administrateurs généraux et les administrateurs de rôle privilégié peuvent créer des révisions d’accès sur des groupes assignables à un rôle.
  - question: >
      Puis-je créer un package d’accès et y placer des groupes qui peuvent être affectés à des rôles Azure AD ?
    answer: "Oui, vous pouvez. L’administrateur général et les administrateurs d’utilisateurs ont la possibilité de placer n’importe quel groupe dans un package d’accès. Rien ne change pour l'Administrateur général, mais les autorisations du rôle Administrateur d'utilisateurs subissent une légère modification. Pour placer un groupe assignable à un rôle dans un package d’accès, vous devez être un administrateur d’utilisateurs et également le propriétaire du groupe en question. Voici le tableau complet qui indique qui peut créer un package d’accès dans la gestion des licences Entreprise :\n\nRôle d’annuaire Azure AD | Rôle de gestion des droits d’utilisation | Peut ajouter un groupe de sécurité\\* | Peut ajouter un groupe Microsoft 365\\* | Peut ajouter une application | Peut ajouter un site SharePoint Online\n----------------------- | --------------------------- | ----------------------- | ------------------------- | ----------- |  -----------------------------\nAdministrateur général | n/a | ✔️ | ✔️ | ✔️  | ✔️\nAdministrateur d'utilisateurs  | n/a  | ✔️  | ✔️  | ✔️\nAdministrateur Intune | Propriétaire de catalogue | ✔️  | ✔️  | &nbsp;  | &nbsp;\nAdministrateur Exchange  | Propriétaire de catalogue  | &nbsp; | ✔️  | &nbsp;  | &nbsp;\nAdministrateur de services fédérés Teams | Propriétaire de catalogue  | &nbsp; | ✔️  | &nbsp;  | &nbsp;\nAdministrateur SharePoint | Propriétaire de catalogue | &nbsp; | ✔️  | &nbsp;  | ✔️ \nAdministrateur d’application | Propriétaire de catalogue  | &nbsp;  | &nbsp; | ✔️  | &nbsp;\nAdministrateur d’application cloud | Propriétaire de catalogue  | &nbsp;  | &nbsp; | ✔️  | &nbsp;\nUtilisateur | Propriétaire de catalogue | Seulement si propriétaire d’un groupe | Seulement si propriétaire d’un groupe | Seulement si propriétaire d’une application  | &nbsp;\n\n\\* Le groupe n’est pas assignable à un rôle ; autrement dit, isAssignableToRole = false. Si un groupe est assignable à un rôle, la personne qui crée le package d’accès doit également être propriétaire du groupe en question.\n"
  - question: >
      Je ne trouve pas l’option « Supprimer l’attribution » dans « Rôles attribués ». Comment supprimer l’attribution de rôle à un utilisateur ?
    answer: >
      Cette réponse s’applique uniquement aux organisations Azure AD Premium P1.


      1. Connectez-vous au [portail Azure](https://portal.azure.com) ou au [centre d’administration Azure AD](https://aad.portal.azure.com) et ouvrez **Azure Active Directory**.

      1. Sélectionnez des utilisateurs et ouvrez un profil utilisateur.

      1. Sélectionnez **Rôles attribués**.

      1. Sélectionnez l’icône d’engrenage. Un volet s’ouvre et peut fournir ces informations. Il y a un bouton « Supprimer » à côté des attributions directes. Pour supprimer une attribution de rôle indirecte, supprimez l’utilisateur du groupe auquel le rôle a été attribué.
  - question: >
      Comment puis-je voir tous les groupes assignables à un rôle ?
    answer: >
      Procédez comme suit :


      1. Connectez-vous au [portail Azure](https://portal.azure.com) ou au [centre d’administration Azure AD](https://aad.portal.azure.com) et ouvrez **Azure Active Directory**.

      1. Sélectionnez **Groupes** > **Tous les groupes**.

      1. Sélectionnez **Ajouter des filtres**.

      1. Filtrez sur **Assignable à un rôle**.
  - question: >
      Comment savoir quel rôle est attribué directement ou indirectement à un principal ?
    answer: >
      Procédez comme suit :


      1. Connectez-vous au [portail Azure](https://portal.azure.com) ou au [centre d’administration Azure AD](https://aad.portal.azure.com) et ouvrez **Azure Active Directory**.

      1. Sélectionnez des utilisateurs et ouvrez un profil utilisateur.

      1. Sélectionnez **Rôles attribués**, puis :

          - Dans les organisations sous licence Azure AD Premium P1 : Sélectionnez l’icône d’engrenage. Un volet s’ouvre et peut fournir ces informations.
          - Dans les organisations sous licence Azure AD Premium P2 : Vous trouverez des informations sur les licences directes et héritées dans la colonne **Appartenance**.
  - question: "Pourquoi la création d’un nouveau groupe est-elle obligatoire pour l’affecter à un rôle ?  \n"
    answer: >
      Si vous affectez un groupe existant à un rôle, le propriétaire du groupe existant peut ajouter d’autres membres à ce groupe sans que les nouveaux membres ne se rendent compte qu’ils recevront le rôle. Parce que les groupes assignables à un rôle sont puissants, nous plaçons de nombreuses restrictions pour les protéger. Vous ne souhaitez pas que le groupe subisse des modifications qui surprendraient la personne qui le gère.
additionalContent: "\n## <a name=\"next-steps\"></a>Étapes suivantes\n\n- [Utiliser des groupes Azure AD pour gérer les attributions de rôles](groups-concept.md)\n- [Créer un groupe assignable à un rôle](groups-create-eligible.md)\n"
