### YamlMime:FAQ
metadata:
  title: Pare-feu d’applications web Azure sur Application Gateway – Forum aux questions
  description: Cet article fournit des réponses aux questions les plus souvent posées concernant le pare-feu d’applications web sur Application Gateway.
  services: web-application-firewall
  author: vhorne
  ms.service: web-application-firewall
  ms.topic: article
  ms.date: 05/05/2020
  ms.author: victorh
  ms.openlocfilehash: d7d5d5c9ea2c0af4933a7bff50ab310d95d29741
  ms.sourcegitcommit: c05e595b9f2dbe78e657fed2eb75c8fe511610e7
  ms.translationtype: HT
  ms.contentlocale: fr-FR
  ms.lasthandoff: 06/11/2021
  ms.locfileid: "112034833"
title: Forum aux questions concernant le pare-feu d’applications web Azure sur Application Gateway
summary: Cet article répond à des questions courantes concernant les fonctions et fonctionnalités du pare-feu d’applications web (WAF) sur Application Gateway.
sections:
- name: Ignoré
  questions:
  - question: >
      Qu’est-ce qu’Azure WAF ?
    answer: >
      Azure WAF est un pare-feu d’applications web qui aide à protéger vos applications web des menaces courantes telles que les injections de code SQL, le script de site à site et autres codes malveillants exploitant des failles de sécurité. Vous pouvez définir une stratégie de pare-feu d’applications web consistant en une combinaison de règles personnalisées et gérées pour contrôler l’accès à vos applications web.


      Une stratégie de pare-feu d’applications web Azure peut être appliquée aux applications web hébergées sur Application Gateway ou Azure Front Door.
  - question: >
      Quelles fonctionnalités la référence (SKU) WAF prend-elle en charge ?
    answer: >
      La référence (SKU) WAF prend-elle en charge toutes les fonctionnalités disponibles dans la référence (SKU) Standard ?
  - question: >
      Comment puis-je surveiller le pare-feu d’application web ?
    answer: >
      Surveillez le pare-feu d'applications web via la journalisation des diagnostics. Pour plus d'informations, consultez [Journalisation des diagnostics et métriques pour Application Gateway](../../application-gateway/application-gateway-diagnostics.md).
  - question: >
      Est-ce que le mode de détection bloque le trafic ?
    answer: >
      Non. Le mode de détection journalise uniquement le trafic qui déclenche une règle de pare-feu d’applications web.
  - question: >
      Puis-je personnaliser les règles de pare-feu d’application web ?
    answer: >
      Oui. Pour plus d’informations, consultez [Personnaliser les règles et groupes de règles WAF](application-gateway-customize-waf-rules-portal.md).
  - question: >
      Quelles sont les règles actuellement disponibles pour WAF ?
    answer: "WAF prend actuellement en charge CRS [2.2.9](application-gateway-crs-rulegroups-rules.md#owasp229), [3.0](application-gateway-crs-rulegroups-rules.md#owasp30) et [3.1](application-gateway-crs-rulegroups-rules.md#owasp31). Ces règles constituent un rempart contre la plupart des 10 principales vulnérabilités identifiées par l'OWASP (Open Web Application Security Project) : \n\n* Protection contre les injections de code SQL\n* Protection contre les scripts intersites\n* Protection contre les attaques web courantes comme l’injection de commande, les dissimulations de requêtes HTTP, la séparation de réponse HTTP et les attaques RFI (Remote File Inclusion)\n* Protection contre les violations de protocole HTTP\n* Protection contre les anomalies de protocole HTTP comme un agent-utilisateur hôte manquant et les en-têtes Accept\n* Protection contre les robots, les crawlers et les scanneurs\n* Détection des erreurs de configuration d’application courantes (par exemple, Apache, IIS, etc.)\n\nPour plus d’informations, consultez [Les 10 principales vulnérabilités identifiées par l'OWASP](https://owasp.org/www-project-top-ten/).\n"
  - question: >
      Quels types de contenu le pare-feu d’applications web (WAF) prend-il en charge ?
    answer: >
      Le WAF d’Application Gateway prend en charge les types de contenu suivants pour les règles gérées :


      * application/json

      * application/xml

      * application/x-www-form-urlencoded

      * multipart/form-data


      Pour les règles personnalisées :


      * application/x-www-form-urlencoded

      * multipart/form-data
  - question: >
      WAF prend-il en charge la protection DDoS ?
    answer: >
      Oui. Vous pouvez activer le service de protection DDoS sur le réseau virtuel sur lequel la passerelle d’application est déployée. Ainsi, le service Azure DDoS Protection protège aussi l’adresse IP virtuelle de la passerelle d’application.


      ### <a name="does-waf-store-customer-data"></a>Le pare-feu d'applications web stocke-t-il les données client ?


      Non, le pare-feu d'applications web ne stocke pas les données client.
additionalContent: "\n## <a name=\"next-steps\"></a>Étapes suivantes\n\n- En savoir plus sur le [pare-feu d’application web Azure](../overview.md).\n- En savoir plus sur [Azure Front Door](../../frontdoor/front-door-overview.md)."
